# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: 'windows-latest'

steps:

- task: DotNetCoreCLI@2
  displayName: 'restore Account.Api'
  inputs:
    command: 'restore'
    projects: '**/Account/Api/Api.csproj'
    arguments: '--configuration release'

- task: VSBuild@1
  inputs:
    solution: '**\Account\Api\Api.csproj'
    platform: 'any cpu'
    configuration: 'release'
    msbuildArchitecture: 'x64'

- task: DotNetCoreCLI@2
  displayName: 'Publish Account.Api'
  inputs:
    command: publish
    projects: '**/Account/Api/Api.csproj'
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Account_Api'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: "Upload Artifacts"
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/Account_Api' 
    artifactName: 'Account.Api' 
