# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: 'windows-latest'

steps:

- task: DotNetCoreCLI@2
  displayName: 'restore Account.Api'
  inputs:
    command: 'restore'
    projects: '**/Account/Api/Api.csproj'
    arguments: '--configuration release'

- task: VSBuild@1
  displayName: 'build Account.Api'
  inputs:
    solution: '**/Account/Api/Api.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\Account_Api.zip"'
    configuration: 'release'
    msbuildArchitecture: 'x64'

- task: PublishBuildArtifacts@1
  displayName: "Upload Artifacts"
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/Account/Api/obj/release/netcoreapp3.1/PubTmp/Out' 
    artifactName: 'Account.Api' 
