# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
#----------------------------------------------
- task: DotNetCoreCLI@2
  displayName: 'restore Account.Api'
  inputs:
    command: 'restore'
    projects: '**/Account/Api/Api.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: VSBuild@1
  displayName: 'build Account.Api'
  inputs:
    solution: '**/Account/Api/Api.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\Account_Api_Dev.zip"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'

#--------------------------------------------

- task: DotNetCoreCLI@2
  displayName: 'restore Crypto.Worker'
  inputs:
    command: 'restore'
    projects: '**/Crypto/Worker/Worker.csproj'
    arguments: '--configuration $(buildConfiguration)'

#--------------------------------------------
- task: VSBuild@1
  displayName: 'build Crypto.Worker'
  inputs:
    solution: '**/Crypto/Worker/Worker.csproj'
    #msbuildArgs: '/p:OutputPath=$(build.artifactStagingDirectory)\CryptoWorker\app_data\Jobs\Continuous\CtyptoWorker'
    msbuildArgs: '/p:OutputPath=$(build.artifactStagingDirectory)\Crypto_Api_Dev\app_data\Jobs\Continuous\CtyptoWorker'
    platform: 'x64'
    configuration: '$(buildConfiguration)'
    #--------------------------------------------
- task: DotNetCoreCLI@2
  displayName: 'restore Crypto.Api'
  inputs:
    command: 'restore'
    projects: '**/Crypto/Api/Api.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: VSBuild@1
  displayName: 'build Crypto.Api'
  inputs:
    solution: '**/Crypto/Api/Api.csproj'
    #msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\Crypto_Api_Dev.zip"'
    msbuildArgs: '/p:OutputPath=$(build.artifactStagingDirectory)\Crypto_Api_Dev'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'

#--------------------------------------------
- task: DotNetCoreCLI@2
  displayName: 'restore Gateway.Api'
  inputs:
    command: 'restore'
    projects: '**/Gateway/Api/Api.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: VSBuild@1
  displayName: 'build Gateway.Api'
  inputs:
    solution: '**/Gateway/Api/Api.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\Gateway_Api_Dev.zip"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'

#--------------------------------------------
- task: DotNetCoreCLI@2
  displayName: 'restore Gateway.Admin'
  inputs:
    command: 'restore'
    projects: '**/Gateway/Admin/Admin.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: VSBuild@1
  displayName: 'build Gateway.Admin'
  inputs:
    solution: '**/Gateway/Admin/Admin.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\Gateway_Admin_Dev.zip"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'

#--------------------------------------------
- task: DotNetCoreCLI@2
  displayName: 'restore Gateway.Worker'
  inputs:
    command: 'restore'
    projects: '**/Gateway/Worker/Worker.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: VSBuild@1
  displayName: 'build Gateway.Worker'
  inputs:
    solution: '**/Gateway/Worker/Worker.csproj'
    msbuildArgs: '/p:OutputPath=$(build.artifactStagingDirectory)\GatewayWorker\app_data\Jobs\Continuous\GatewayWorker'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'

#--------------------------------------------
#--------------------------------------------
- task: PublishBuildArtifacts@1
  displayName: "Upload Artifacts"
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Binebase.Api' 
